"""
NEXUS ONE - Security Event Types
"""

LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"
LOGOUT = "LOGOUT"

PASSWORD_CHANGED = "PASSWORD_CHANGED"
PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"

PROFILE_UPDATE = "PROFILE_UPDATE"

TOKEN_REFRESH = "TOKEN_REFRESH"
TOKEN_REFRESH_FAILED = "TOKEN_REFRESH_FAILED"
TOKEN_REVOKED = "TOKEN_REVOKED"

ACCESS_DENIED = "ACCESS_DENIED"
UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"

SUSPICIOUS_REQUEST = "SUSPICIOUS_REQUEST"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

USER_CREATED = "USER_CREATED"
USER_UPDATED = "USER_UPDATED"
USER_DELETED = "USER_DELETED"

ADMIN_ACTION = "ADMIN_ACTION"
